version: "3.8"

services:
  node:
    image: node:18
    container_name: node
    volumes:
      - ./node_server:/app
    working_dir: /app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
      - postgres

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

  mongodb:
    image: mongo:5
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-storage:/data/db
    env_file:
      - .env
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  mongo-storage:
    driver: local
  postgres-storage:
    driver: local
