services:
  node:
    build:
      context: ./node_server
      dockerfile: ../_infrastructure/docker/node/Dockerfile
    container_name: node
    # volumes:
    #   - ./node_server:/app
    working_dir: /app
    ports:
      - "3001:3001"
    command: /bin/bash -c "npm install && npm start"
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
      - postgres

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:5
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-storage:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./_infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./_infrastructure/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./_infrastructure/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./_infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
      - ./_infrastructure/grafana/config/grafana.ini:/etc/grafana/grafana.ini

  locust_exporter:
    image: containersol/locust_exporter
    environment:
      - LOCUST_EXPORTER_URI=http://host.docker.internal:8089
    ports:
      - "9646:9646"

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://admin:password@host.docker.internal:5432/mydb?sslmode=disable
      - POSTGRES_EXPORTER_PASSWORD=${PG_PASSWORD}
      - POSTGRES_EXPORTER_USER=${PG_USER}
      - POSTGRES_EXPORTER_DB=${PG_DATABASE}
      - POSTGRES_EXPORTER_PORT=${PG_PORT}
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    env_file:
      - .env
  redis_exporter:
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=host.docker.internal:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXPORTER_PASSWORD=${REDIS_EXPORTER_PASSWORD}
    ports:
      - "9121:9121"
    depends_on:
      - redis
    env_file:
      - .env
  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - MONGODB_USER=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DATABASE}
    ports:
      - "9216:9216"
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongo-storage:
    driver: local
  postgres-storage:
    driver: local
  grafana-data:
    driver: local
