services:
  node:
    image: node:18
    container_name: node
    volumes:
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    working_dir: /app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-storage:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-storage:/var/lib/postgresql/data
volumes:
  mongo-storage:
    driver: local
  postgres-storage:
    driver: local
