---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Ensure containerd directory exists
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Generate containerd configuration
  command: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Enable CRI plugin in containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: "^disabled_plugins =.*"
    line: "disabled_plugins = []"
    state: present
  notify: Restart containerd

- name: Ensure containerd service is running
  systemd:
    name: containerd
    state: started
    enabled: yes

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
