---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*\sswap\s'
    state: absent

- name: Load br_netfilter kernel module
  command: modprobe br_netfilter
  changed_when: false
  ignore_errors: true

- name: Persist br_netfilter module
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: br_netfilter
    create: yes
    state: present
    mode: "0644"

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
    ignoreerrors: "{{ item.ignoreerrors | default(false) }}"
  loop:
    - {
        name: "net.bridge.bridge-nf-call-iptables",
        value: "1",
        ignoreerrors: true,
      }
    - {
        name: "net.bridge.bridge-nf-call-ip6tables",
        value: "1",
        ignoreerrors: true,
      }
    - { name: "net.ipv4.ip_forward", value: "1", ignoreerrors: false }
